// Frases de artigos científicos de hidrologia com lacuna (Cloze)
// "blank" é a palavra/termo correto que falta no lugar de ___
const CLOZE_DATA = [
  { sentence: "Urban ___ significantly increases peak discharge during intense rainfall events.", blank: "runoff" },
  { sentence: "The 100-year flood ___ period was used as the design standard for the levee system.", blank: "return" },
  { sentence: "Soil ___ conductivity determines how quickly water infiltrates into the ground.", blank: "hydraulic" },
  { sentence: "The city's ___ drainage network was overwhelmed during the storm event.", blank: "urban" },
  { sentence: "The ___ discharge occurred approximately two hours after peak rainfall intensity.", blank: "peak" },
  { sentence: "The ___ shows how streamflow rises and falls in response to a rainfall event.", blank: "hydrograph" },
  { sentence: "The ___ area defines the boundary that drains into a single outlet point.", blank: "catchment" },
  { sentence: "Urban ___ depends on the capacity of infrastructure to adapt to extreme events.", blank: "resilience" },
  { sentence: "Flood ___ mapping helps identify which neighborhoods are most at risk.", blank: "vulnerability" },
  { sentence: "___ mapping was used to delineate the extent of the floodplain.", blank: "GIS" },
  { sentence: "___ surfaces such as asphalt and concrete prevent natural infiltration.", blank: "Impervious" },
  { sentence: "Construction within the ___ increases the risk of property damage during floods.", blank: "floodplain" },
  { sentence: "The ___ basin temporarily stores excess stormwater before releasing it slowly.", blank: "detention" },
  { sentence: "Sandy soils generally exhibit a higher ___ rate than clay soils.", blank: "infiltration" },
  { sentence: "The ___ boundary was delineated using a digital elevation model.", blank: "watershed" },
  { sentence: "___ equation is commonly used to estimate flow velocity in open channels.", blank: "Manning's" },
  { sentence: "A calibrated hydraulic ___ was used to simulate water levels along the river.", blank: "model" },
  { sentence: "___ intensity is a critical input parameter for stormwater design.", blank: "Precipitation" },
  { sentence: "The drainage ___ was modeled using SWMM software.", blank: "network" },
  { sentence: "Flood frequency ___ estimates the probability of extreme hydrological events.", blank: "analysis" },
  { sentence: "The ___ zone along the riverbank provides both ecological and flood buffer functions.", blank: "riparian" },
  { sentence: "Green infrastructure can help mitigate the urban heat ___ effect.", blank: "island" },
  { sentence: "___ infrastructure reduces runoff while providing additional ecosystem services.", blank: "Green" },
  { sentence: "___ pavement allows stormwater to infiltrate directly through the surface.", blank: "Permeable" },
  { sentence: "___ cells are designed to filter pollutants from stormwater before infiltration.", blank: "Bioretention" },
  { sentence: "The ___ was undersized for the observed peak discharge, causing local flooding.", blank: "culvert" },
  { sentence: "The ___ failed during the extreme flood event, leading to widespread inundation.", blank: "levee" },
  { sentence: "Storm ___ combined with heavy rainfall worsened coastal flooding conditions.", blank: "surge" },
  { sentence: "The digital elevation model, or ___, was used to extract slope and flow direction.", blank: "DEM" },
  { sentence: "___ is widely used by engineers to simulate urban drainage systems.", blank: "SWMM" },
];
