// Vocabulário técnico de engenharia urbana / hidrologia para flashcards
const FLASHCARDS_DATA = [
  { term: "stormwater runoff", translation: "escoamento superficial de águas pluviais", example: "Stormwater runoff increases significantly in urbanized catchments." },
  { term: "flood return period", translation: "período de retorno de enchente", example: "The design considered a 100-year flood return period." },
  { term: "hydraulic conductivity", translation: "condutividade hidráulica", example: "Soil hydraulic conductivity controls infiltration rates." },
  { term: "urban drainage", translation: "drenagem urbana", example: "The city upgraded its urban drainage network after the floods." },
  { term: "peak discharge", translation: "vazão de pico", example: "Peak discharge occurred two hours after the rainfall event." },
  { term: "hydrograph", translation: "hidrograma", example: "The hydrograph shows the rise and fall of flow over time." },
  { term: "catchment area", translation: "área de captação / bacia hidrográfica", example: "The catchment area drains into the main river channel." },
  { term: "resilience", translation: "resiliência", example: "Urban resilience depends on adaptive infrastructure planning." },
  { term: "vulnerability", translation: "vulnerabilidade", example: "Flood vulnerability mapping helps prioritize interventions." },
  { term: "GIS mapping", translation: "mapeamento por SIG (Sistema de Informação Geográfica)", example: "GIS mapping was used to delineate the floodplain." },
  { term: "impervious surface", translation: "superfície impermeável", example: "Impervious surfaces reduce natural infiltration in cities." },
  { term: "floodplain", translation: "planície de inundação", example: "Construction in the floodplain increases flood risk." },
  { term: "detention basin", translation: "bacia de detenção", example: "The detention basin temporarily stores excess runoff." },
  { term: "infiltration rate", translation: "taxa de infiltração", example: "Sandy soils have a higher infiltration rate than clay." },
  { term: "watershed", translation: "bacia hidrográfica", example: "The watershed boundary was defined using the digital elevation model." },
  { term: "Manning's equation", translation: "equação de Manning", example: "Manning's equation estimates flow velocity in open channels." },
  { term: "hydraulic model", translation: "modelo hidráulico", example: "The hydraulic model simulated water levels along the river." },
  { term: "precipitation intensity", translation: "intensidade de precipitação", example: "Precipitation intensity is a key input for design storms." },
  { term: "drainage network", translation: "rede de drenagem", example: "The drainage network was modeled using SWMM." },
  { term: "flood frequency analysis", translation: "análise de frequência de enchentes", example: "Flood frequency analysis estimates the probability of extreme events." },
  { term: "riparian zone", translation: "zona ripária / mata ciliar", example: "The riparian zone provides ecological and flood buffer functions." },
  { term: "urban heat island", translation: "ilha de calor urbana", example: "Green infrastructure can mitigate the urban heat island effect." },
  { term: "green infrastructure", translation: "infraestrutura verde", example: "Green infrastructure reduces runoff while providing ecosystem services." },
  { term: "permeable pavement", translation: "pavimento permeável", example: "Permeable pavement allows water to infiltrate through the surface." },
  { term: "bioretention", translation: "biorretenção", example: "Bioretention cells filter pollutants from stormwater runoff." },
  { term: "culvert", translation: "bueiro / galeria", example: "The culvert was undersized for the observed peak discharge." },
  { term: "levee", translation: "dique", example: "The levee failed during the extreme flood event." },
  { term: "storm surge", translation: "ressaca / maré de tempestade", example: "Storm surge combined with heavy rainfall worsened coastal flooding." },
  { term: "DEM (digital elevation model)", translation: "modelo digital de elevação", example: "The DEM was used to extract slope and flow direction." },
  { term: "SWMM", translation: "SWMM (Storm Water Management Model)", example: "SWMM is widely used to simulate urban drainage systems." },
];
