// Vocabulário acadêmico em inglês comum em artigos, teses e dissertações
const VOCAB_DATA = [
  { term: "hypothesis", translation: "hipótese" },
  { term: "methodology", translation: "metodologia" },
  { term: "framework", translation: "arcabouço / referencial teórico" },
  { term: "findings", translation: "resultados / achados" },
  { term: "literature review", translation: "revisão de literatura" },
  { term: "data collection", translation: "coleta de dados" },
  { term: "sample size", translation: "tamanho da amostra" },
  { term: "variable", translation: "variável" },
  { term: "significant", translation: "significativo" },
  { term: "correlation", translation: "correlação" },
  { term: "qualitative", translation: "qualitativo" },
  { term: "quantitative", translation: "quantitativo" },
  { term: "peer-reviewed", translation: "revisado por pares" },
  { term: "citation", translation: "citação" },
  { term: "bibliography", translation: "bibliografia" },
  { term: "abstract", translation: "resumo" },
  { term: "thesis statement", translation: "tese / argumento central" },
  { term: "research question", translation: "questão de pesquisa" },
  { term: "limitations", translation: "limitações" },
  { term: "implications", translation: "implicações" },
  { term: "to argue", translation: "argumentar" },
  { term: "to assume", translation: "assumir / supor" },
  { term: "to conclude", translation: "concluir" },
  { term: "to analyze", translation: "analisar" },
  { term: "to demonstrate", translation: "demonstrar" },
  { term: "to investigate", translation: "investigar" },
  { term: "evidence", translation: "evidência" },
  { term: "outcome", translation: "resultado / desfecho" },
  { term: "scope", translation: "escopo" },
  { term: "supervisor / advisor", translation: "orientador(a)" },
  { term: "peer", translation: "colega de área / par" },
  { term: "draft", translation: "rascunho / versão preliminar" },
  { term: "feedback", translation: "retorno / parecer" },
  { term: "deadline", translation: "prazo final" },
  { term: "grant", translation: "bolsa / financiamento" },
  { term: "fieldwork", translation: "trabalho de campo" },
  { term: "theoretical framework", translation: "referencial teórico" },
  { term: "case study", translation: "estudo de caso" },
  { term: "to cite", translation: "citar" },
  { term: "plagiarism", translation: "plágio" },
  { term: "defense (thesis defense)", translation: "defesa (de tese/dissertação)" },
];
